[package]
name = "json-serde"
version = "0.0.1-alpha.1"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/json-serde"
description = "Runtime serde helpers for esoteric JSON semantics"
keywords = ["serde", "json", "json-schema", "codegen"]
categories = ["encoding"]
exclude = [".github", "rust-toolchain.toml"]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
schemars08 = ["dep:schemars08"]
schemars1 = ["dep:schemars1"]

[dependencies]
serde_core = "1.0.228"
schemars08 = { package = "schemars", version = "0.8.22", optional = true, default-features = false }
schemars1 = { package = "schemars", version = "1.2.1", optional = true, default-features = false }

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
schemars08 = { package = "schemars", version = "0.8.22", features = ["derive"] }
schemars1 = { package = "schemars", version = "1.2.1", features = ["derive"] }
